server:
  port: 8080
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.lastnight2022.cc.mybatis.entity
spring:
  datasource:
    url: jdbc:mysql://192.168.1.13:3306/AI_Models_Manager?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: tom
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
#      uri: mongodb://username:password@localhost:27017/mydb?authSource=admin
      uri: mongodb://192.168.1.13:27017/admin
#    redis:
#      host: 192.168.1.13
#      port: 6379
#      password: 123456
#      database: 0
#      lettuce:
#        pool:
#          enabled: true
#          max-active: 8
#          max-idle: 8
#          min-idle: 0
#          max-wait: 2000ms
