server:
  port: 8080
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.lastnight2022.cc.models
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://192.168.1.13:3306/AI_Models_Manager?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: tom
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
#      uri: mongodb://username:password@localhost:27017/mydb?authSource=admin
      uri: mongodb://192.168.1.13:27017/admin
    redis:
      host: 192.168.1.13
      port: 6379
      password: 123456
      database: 0
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 2000ms
logging:
  level:
    com.lastnight2022.cc.mapper: DEBUG
    # 更详细的执行日志（可选）
    org.mybatis: TRACE
    java.sql.Connection: TRACE
    java.sql.Statement: DEBUG
    java.sql.PreparedStatement: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 自定义日志格式