server:
  port: 8080
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.lastnight2022.cc.mybatis.entity
spring:
  datasource:
    url: jdbc:mysql://192.168.1.13:3306/AI_Models_Manager?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: tom
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


